# Generated by Django 6.0 on 2026-02-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Format +233', max_length=15, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.IntegerField(default=10, help_text='Number of free queries remaining')),
                ('is_active', models.BooleanField(default=True, help_text='If False, user receives no replies')),
            ],
            options={
                'verbose_name': 'SMS User',
                'verbose_name_plural': 'SMS Users',
            },
        ),
    ]
